name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."


  test:
    runs-on: ubuntu-latest
    container: python:3.8
    defaults:
      run:
        working-directory: ./backend/secfit
    steps:
    # this configures Django application to use attached postgres database that is run on `postgres` host
      - uses: actions/checkout@v1
      - working-directory: ./
        run: apt-get update -qy
      - run: pip install -r requirements.txt

  staging:
    runs-on: ubuntu-latest
    container: ruby
        defaults:
      run:
        working-directory: ./
    steps:
      - run: apt-get update -qy
      - run: apt-get install -y ruby-dev
      - run: gem install dpl
      - run: dpl --provider=heroku --app=tdt4242-ex2-frontend --api-key=${{ secrets.HEROKU_STAGING_API_KEY }}
      - run: dpl --provider=heroku --app=tdt4242-ex2-backend --api-key=${{ secrets.HEROKU_STAGING_API_KEY }}